"""Regenerate every number quoted in the README.

    python3 evidence/run_evidence.py > evidence/results.md

Everything printed here comes from a run performed by this script. Nothing is
copied forward from a previous run, and nothing is estimated.
"""

import os
import platform
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ebb import scenes
from ebb.fixed import SCALE
from ebb.world import World, drift_axis, undrift_axis

SCENE_LIST = [
    ("drop", scenes.drop, "8 balls let go in a row, under gravity"),
    ("billiards", scenes.billiards, "6 balls, no gravity: the elastic control"),
    ("scatter", scenes.scatter, "14 smaller balls, light gravity"),
    ("single", scenes.single, "1 ball: no pair can ever contact"),
]


def round_trip(scene_fn, steps):
    w = scene_fn()
    start = w.state()
    t0 = time.perf_counter()
    w.run(steps)
    forward_s = time.perf_counter() - t0
    moved = w.state() != start
    contacts = w.contacts_resolved
    tape_bytes = w.tape.bytes_serialised()
    tape_entries = len(w.tape)
    snap_frame = w.snapshot_bytes_per_frame()
    t0 = time.perf_counter()
    w.unrun(steps)
    back_s = time.perf_counter() - t0
    return {
        "steps": steps,
        "bodies": len(w),
        "moved": moved,
        "exact": w.state() == start,
        "tape_empty_after": len(w.tape) == 0,
        "contacts": contacts,
        "tape_entries": tape_entries,
        "tape_bytes": tape_bytes,
        "bits_per_contact": (8.0 * tape_bytes / contacts) if contacts else 0.0,
        "snapshot_bytes_per_frame": snap_frame,
        "snapshot_bytes_total": snap_frame * steps,
        "ratio": (snap_frame * steps) / tape_bytes if tape_bytes else float("inf"),
        "forward_s": forward_s,
        "back_s": back_s,
        "steps_per_s": steps / forward_s if forward_s else 0.0,
    }


def wall_rule_enumeration(lo=0, hi=40):
    span = hi - lo
    images = {}
    collisions = 0
    inverted = 0
    total = 0
    for x in range(lo, hi + 1):
        for v in range(-span, span + 1):
            total += 1
            out = drift_axis(x, v, lo, hi)
            if out in images:
                collisions += 1
            images[out] = (x, v)
            if undrift_axis(out[0], out[1], lo, hi) == (x, v):
                inverted += 1
    return total, len(images), collisions, inverted


def naive_wall_rule_enumeration(lo=0, hi=40, reach=8):
    """The rule without the half-unit offset, for contrast."""
    images = {}
    collisions = 0
    total = 0
    for x in range(lo, hi + 1):
        for v in range(-reach, reach + 1):
            total += 1
            t = x + v
            if t > hi:
                out = (2 * hi - t, -v)
            elif t < lo:
                out = (2 * lo - t, -v)
            else:
                out = (t, v)
            if out in images and images[out] != (x, v):
                collisions += 1
            images[out] = (x, v)
    return total, collisions


def main():
    print("# Evidence — ebb, milestone 1")
    print()
    print("Generated by `python3 evidence/run_evidence.py`. Every number below comes")
    print("from this run.")
    print()
    print("- date (UTC): %s" % time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime()))
    print("- python: %s" % sys.version.split()[0])
    print("- platform: %s %s" % (platform.system(), platform.machine()))
    print("- fixed-point scale: %d sub-units per world unit" % SCALE)
    print("- dependencies: none (standard library only)")
    print()

    print("## 1. Round trip: does stepping backwards land on the exact start state?")
    print()
    print("`exact` compares the whole integer state -- time, every position, every")
    print("velocity -- not a tolerance.")
    print()
    print("| scene | bodies | steps | moved | exact return | tape empty after |")
    print("| --- | ---: | ---: | --- | --- | --- |")
    rows = {}
    for name, fn, _ in SCENE_LIST:
        r = round_trip(fn, 10_000)
        rows[name] = r
        print("| %s | %d | %d | %s | **%s** | %s |"
              % (name, r["bodies"], r["steps"], r["moved"], r["exact"], r["tape_empty_after"]))
    print()

    print("## 2. A longer run")
    print()
    long_r = round_trip(scenes.drop, 100_000)
    print("| scene | steps | contacts | exact return | forward | backward |")
    print("| --- | ---: | ---: | --- | ---: | ---: |")
    print("| drop | %d | %d | **%s** | %.2f s | %.2f s |"
          % (long_r["steps"], long_r["contacts"], long_r["exact"],
             long_r["forward_s"], long_r["back_s"]))
    print()

    print("## 3. What reversal costs")
    print()
    print("The residue tape is the only thing kept in order to go backwards: one")
    print("integer per contact event, nothing per frame and nothing per body. The")
    print("snapshot column is what storing every frame would cost instead, using the")
    print("same varint encoding for both sides, so the two are comparable.")
    print()
    print("| scene | steps | contacts | tape entries | tape bytes | bits per contact | snapshot bytes | ratio |")
    print("| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |")
    for name, _, _ in SCENE_LIST:
        r = rows[name]
        ratio = "n/a" if r["tape_bytes"] == 0 else "%.0fx" % r["ratio"]
        print("| %s | %d | %d | %d | %d | %.1f | %d | %s |"
              % (name, r["steps"], r["contacts"], r["tape_entries"], r["tape_bytes"],
                 r["bits_per_contact"], r["snapshot_bytes_total"], ratio))
    print()
    print("The `single` row is the null control: one ball cannot contact anything, so")
    print("the tape stays at zero bytes and the rewind is genuinely free.")
    print()

    print("## 4. Controls")
    print()

    a, b = scenes.drop(), scenes.drop()
    a.run(5_000)
    b.run(5_000)
    print("**Determinism.** Two independent runs of the same scene, 5,000 steps: states")
    print("identical = %s, residue tapes identical = %s."
          % (a.state() == b.state(), a.tape.items == b.tape.items))
    print()

    w = scenes.billiards()
    e0 = w.kinetic_energy()
    w.run(10_000)
    e1 = w.kinetic_energy()
    print("**Energy, elastic scene.** With no gravity the kinetic energy is the whole")
    print("energy budget, so it should stay put. Over 10,000 steps: %d -> %d, a change"
          % (e0, e1))
    print("of %.4f%%. The residual is the integer rounding in contact resolution, which"
          % (100.0 * abs(e1 - e0) / e0))
    print("is exactly the information the tape records.")
    print()

    # Build a contact that is certain to happen, rather than hoping one is pending.
    w = World.from_units((0, 0, 12, 8))
    w.add_disc_units(5.0, 4.0, 0.05, 0.012, 0.5)
    w.add_disc_units(5.8, 4.3, -0.04, -0.01, 0.5)
    assert w.overlapping_pairs(), "the momentum control must actually exercise a contact"
    p0 = w.momentum()
    before = (list(w.vx), list(w.vy))
    w._contacts(1)
    p1 = w.momentum()
    changed = (list(w.vx), list(w.vy)) != before
    print("**Momentum across contact.** The impulse is applied equal and opposite as")
    print("integers, so momentum is conserved to the last bit: %s -> %s, with the"
          % (p0, p1))
    print("velocities genuinely changed by the contact: %s." % changed)
    print()

    total, images, collisions, inverted = wall_rule_enumeration()
    print("**Wall rule, exhaustive.** Every state on a 41-position axis with every")
    print("velocity the rule accepts: %d states, %d distinct images, %d collisions,"
          % (total, images, collisions))
    print("%d of %d inverted exactly." % (inverted, total))
    print()
    ntotal, ncollisions = naive_wall_rule_enumeration()
    print("**Wall rule without the half-unit offset**, the same enumeration over a")
    print("smaller velocity range: %d states, %d of them landing on a state another"
          % (ntotal, ncollisions))
    print("state also reaches. That is why the offset is there: without it the step is")
    print("not a bijection and no amount of bookkeeping recovers the lost state.")
    print()

    print("## 4b. How much of the contact activity is the same pair, over and over")
    print()
    print("Milestone 1 resolves every overlapping pair on every step. A pair that stays")
    print("overlapped therefore has its relative normal velocity exchanged repeatedly,")
    print("which is reversible but is not how contact should behave. This measures how")
    print("often that happens, so the limitation is a number rather than a hedge.")
    print()
    print("| scene | steps | contact events | pairs newly overlapping | repeats of a pair already overlapping | repeat share |")
    print("| --- | ---: | ---: | ---: | ---: | ---: |")
    for name, fn, _ in SCENE_LIST:
        w = fn()
        previous = set()
        fresh = repeats = 0
        for _ in range(5_000):
            w.step()
            current = set(w.overlapping_pairs())
            fresh += len(current - previous)
            repeats += len(current & previous)
            previous = current
        events = fresh + repeats
        share = (100.0 * repeats / events) if events else 0.0
        print("| %s | 5000 | %d | %d | %d | %.1f%% |"
              % (name, events, fresh, repeats, share))
    print()
    print("Milestone 2 replaces this rule with one that keeps bodies from overlapping at")
    print("all, which is both better contact physics and, being a reflection in the")
    print("relative coordinate, the same trick that already makes the walls reversible.")
    print()

    print("## 5. Speed")
    print()
    print("Single-threaded pure Python, no attempt at optimisation yet.")
    print()
    print("| scene | bodies | steps per second, forward |")
    print("| --- | ---: | ---: |")
    for name, _, _ in SCENE_LIST:
        r = rows[name]
        print("| %s | %d | %.0f |" % (name, r["bodies"], r["steps_per_s"]))
    print()

    print("## 6. What this run does not show")
    print()
    print("- No rotation, no polygons, no friction, no restitution: milestone 1 is discs")
    print("  with elastic contact. Those milestones are listed in `TASKS.json`.")
    print("- Bodies that stay overlapped for several steps have their relative normal")
    print("  velocity exchanged on every one of those steps. It is reversible, and it is")
    print("  not good contact physics. See the status section of the README.")
    print("- The comparison against snapshots is a storage comparison only. No claim is")
    print("  made here about speed against any other engine.")


if __name__ == "__main__":
    main()
